name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'factory-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/Monitoring-Machine
            git pull origin master
            cd factory-backend
            npm install --production
            pm2 restart factory-backend